"""empty message

Revision ID: 4d4356cf3330
Revises: fd81f2a2e9a6
Create Date: 2020-03-18 18:01:25.456047

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4d4356cf3330'
down_revision = 'fd81f2a2e9a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_hour', sa.Column('datetime', sa.DateTime(), nullable=False))
    op.drop_column('report_hour', 'date')
    op.drop_column('report_hour', 'hour')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_hour', sa.Column('hour', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('report_hour', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('report_hour', 'datetime')
    # ### end Alembic commands ###
