"""empty message

Revision ID: 905c1c80a42f
Revises: 4fba28303e55
Create Date: 2020-03-18 17:44:05.195251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '905c1c80a42f'
down_revision = '4fba28303e55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'visitorship_total_capacity_key', 'visitorship', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'visitorship_total_capacity_key', 'visitorship', ['total_capacity'])
    # ### end Alembic commands ###
