"""empty message

Revision ID: fd81f2a2e9a6
Revises: 905c1c80a42f
Create Date: 2020-03-18 17:52:40.324530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd81f2a2e9a6'
down_revision = '905c1c80a42f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_hour', sa.Column('date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report_hour', 'date')
    # ### end Alembic commands ###
