"""empty message

Revision ID: 167e5b31ca3c
Revises: 
Create Date: 2020-03-18 17:29:03.756639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '167e5b31ca3c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_hour',
    sa.Column('hour', sa.DateTime(), nullable=False),
    sa.Column('gender', sa.String(length=80), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('hour', 'gender')
    )
    op.create_table('visitorship',
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('total_capacity', sa.Integer(), nullable=False),
    sa.Column('modified_timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('report_date'),
    sa.UniqueConstraint('total_capacity')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visitorship')
    op.drop_table('report_hour')
    # ### end Alembic commands ###
